# Generated by Django 5.1.8 on 2025-04-13 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("event", "0038_eventextralink"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenmetricsToken",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("token", models.CharField(max_length=50)),
                (
                    "event",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pretalx_openmetrics_token",
                        to="event.event",
                    ),
                ),
            ],
        ),
    ]
