# Generated by Django 5.1.8 on 2025-04-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0036_alter_event_header_image_alter_event_logo"),
        ("pretalx_openmetrics", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="openmetricstoken",
            constraint=models.UniqueConstraint(fields=("event",), name="unique_event"),
        ),
    ]
